name: Matric Demo
on: push
jobs: 
  build:
    continue-on-error: true
    strategy:
      matrix: 
        node-version: [12, 16, 18]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 20
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build


