name: Reusable output deploy
on: 
  workflow_call:
    inputs: 
      artifact-name:
        description: "The name of the artifact"
        required: true
        default: dist
        type: string
    # secrets:
    #   some-secrets:
    #     required: false
    outputs: 
      result:
        description: "The results fo deployment"
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: list files
        run: ls
      - name: Output information
        run: |
          echo "This is a test reuse workflow"
    # For output demo test
      - name: set result output
        id: set-result
        run: |
          echo "step-result=success" >> $GITHUB_OUTPUT